In [3]:
import pandas as pd

# open the .txt file which have names of all videos
f = open("classList.txt", "r")
temp = f.read()
videos = temp.split('\n')

# creating a dataframe having video names
all_vids = pd.DataFrame()
all_vids['video_name'] = videos
all_vids = all_vids[:-1]
all_vids.head()

# creating tags for all videos
video_tags = []
for i in range(all_vids.shape[0]):
    video_tags.append(all_vids['video_name'][i].split('/')[0])
    
all_vids['tag'] = video_tags
all_vids.shape[0]
all_vids

                                        video_name             tag
0      ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01.avi  ApplyEyeMakeup
1      ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c02.avi  ApplyEyeMakeup
2      ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c03.avi  ApplyEyeMakeup
3      ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c04.avi  ApplyEyeMakeup
4      ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c05.avi  ApplyEyeMakeup
...                                            ...             ...
13315                      YoYo/v_YoYo_g25_c01.avi            YoYo
13316                      YoYo/v_YoYo_g25_c02.avi            YoYo
13317                      YoYo/v_YoYo_g25_c03.avi            YoYo
13318                      YoYo/v_YoYo_g25_c04.avi            YoYo
13319                      YoYo/v_YoYo_g25_c05.avi            YoYo

[13320 rows x 2 columns]